projects/webportfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :videos
  resources :lyrics
  resources :poems
  resources :pictures
  resources :home do
    get 'about_us', on: :collection
    get 'contact_us', on: :collection
    post 'messages', on: :collection
  end
  root to: 'home#index'
namespace :admin do
  resources :videos
  resources :lyrics
  resources :poems
  resources :pictures
end

end

projects/webportfolio/app/models/lyric.rb
class Lyric < ActiveRecord::Base
end

projects/webportfolio/app/controllers/admin/lyrics_controller.rb
class Admin::LyricsController < ApplicationController
  layout "sidebar"
  before_filter :authenticate_admin!
def new
@lyric = Lyric.new
end
def show
@lyric=Lyric.find(params[:id])

@file=File.open("#{Rails.root.join('reads', "#{@lyric.title}")}")
end
def index
@lyrics = Lyric.all
end
def create
@lyric = Lyric.new(user_params)
if Dir.exists?("reads")
  f = File.open("#{Rails.root.join('reads', "#{user_params[:title]}")}", "w")
  f.write("#{user_params[:text]}")
  f.close #=
else
Dir.mkdir("reads")
f = File.open("#{Rails.root.join('reads', "#{user_params[:title]}")}", "w")
f.write("#{user_params[:text]}")
f.close #=
end
if @lyric.save
 flash[:success] = 'Lyric added!'
 redirect_to admin_lyrics_path
else
 render 'new'
end
end
protected
def user_params
  params.require(:lyric).permit(:title, :description, :text,:read_type)
end

end

projects/webportfolio/app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  layout "sidebar"
def new
@lyric = Lyric.new
end
def show
@lyric=Lyric.find(params[:id])

@file=File.open("#{Rails.root.join('reads', "#{@lyric.title}")}")
end
def index
	@lyrics1 = Lyric.where('read_type=?','couplet').order('created_at DESC').paginate(:page => params[:page], :per_page => 16)
	@lyrics = Lyric.where('read_type=?','poem').order('created_at DESC').paginate(:page => params[:page], :per_page => 16)
end
def read
	@lyrics = Lyric.where('read_type=?','poem')
end
def create
@lyric = Lyric.new(user_params)
if Dir.exists?("reads")
  f = File.open("#{Rails.root.join('reads', "#{user_params[:title]}")}", "w")
  f.write("#{user_params[:text]}")
  f.close #=
else
Dir.mkdir("reads")
f = File.open("#{Rails.root.join('reads', "#{user_params[:title]}")}", "w")
f.write("#{user_params[:text]}")
f.close #=
end
if @lyric.save
 flash[:success] = 'Lyric added!'
 redirect_to lyrics_path
else
 render 'new'
end
end
protected
def user_params
  params.require(:lyric).permit(:title, :description, :text,:read_type)
end

end

projects/webportfolio/app/helpers/lyrics_helper.rb
module LyricsHelper
end

projects/webportfolio/app/views/lyrics/index.html.erb
<% if @lyrics.any?||@lyrics1.any? %>

<div class="col-md-2 col-lg-2"></div>
    <div class="lyrics-container-wrapper col-md-8 col-xs-12 col-sm-12 col-lg-8 ">
<div class="row">
<div class="col-md-12">
<%= bootstrap_form_tag url:lyrics_path, method: :get, remote: true,html: {class: 'read-search'} do |f| %>
                 <input type = "radio" id = "sort_ri" name = "sort" 
                 value = "poem" checked = "checked" class="sort"/>
                <%= f.label :sort_by, "Poems",class:'filter' %> 
                <input type = "radio" id = "sort_ra" name = "sort" 
                 value = "couplet" class="sort"/>
                <%= f.label :sort_by, "Couplets",class:'filter'%></span>
                <%end%>
</div>
</div>
<div class="read_poem">
<% @lyrics.in_groups_of(2) do |group| %>
              <% group.each do |lyric| %>
              
                <% if lyric %>
                  <%= link_to(lyric_path(lyric),target: '_blank') do %>
                <div class="row activity-table">
              <div class="lyrics-title col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <span class="captions"><%=lyric.title%></span>
                   </div>  
<div class="lyrics-description col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <span class="captions"><%=lyric.description%></span>
                   </div>
</div>
                <% end %>
                <%end%>
       
        <% end %>
    <% end %>
    <%= will_paginate @lyrics %>
  </div>
<% end %>
<div class="read_couplet hide">
<% @lyrics1.in_groups_of(2) do |group| %>
              <% group.each do |lyric| %>
              
                <% if lyric %>
                <%= link_to(lyric_path(lyric),target: '_blank') do %>

                <div class="row activity-table">
              <div class="lyrics-title col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <span class="captions"><%=lyric.title%></span>
                   </div>  
<div class="lyrics-description col-md-6 col-xs-6 col-sm-6 col-lg-6">
                <span class="captions"><%=lyric.description%></span>
                   </div>
</div>
                <% end %>
 <%end%>
        <% end %>
    <% end %>
     <%= will_paginate @lyrics1 %>
  </div>
</div>
</div>

projects/webportfolio/app/views/lyrics/new.html.erb
<%= form_for(@lyric) do |f| %>
    <div class="col-md-6">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: 'form-control', required: true %>
        <%= f.label :description %><br />
        <%= f.text_field :description, class: 'form-control', required: true %>
          <%= f.label :text%><br />
          <%= f.text_area :text, :class => 'ckeditor', required: true %>
          <%= f.select :read_type, options_for_select([["Select One", ""], "poem", "couplet"]), :required => 'true' %>
        <span class="help-block">A link to the poem  on YouTube channel.</span>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
  <% end %>
<script>
$('.ckeditor').ckeditor({
  // optional config
});
</script>

projects/webportfolio/app/views/lyrics/show.html.erb
<div class="wrapper">

  <div class="gallerycontain">
    <div class="col-md-3 col-xs-3 col-sm-3 col-lg-3 hiddenbuttons">
    </div>
    <div class="col-md-9 col-xs-9 col-sm-9 col-lg-9 side">
      <div class="col-md-9 col-xs-9 col-sm-9 col-lg-9">
      <% @file.each do |f| %>
        <%= f.html_safe %>
           <% end %>
      <%@file.close%>
      </div>
      <div class="col-md-3 col-xs-3 col-sm-3 col-lg-3 sign">
        <%=image_tag "duggusignnewtest.png",size: "220x300"%>
      </div>
  </div>
  </div>
</div>
<style>
.side{
  margin-top: 22px;
  overflow-y: auto;
}

.sign{
  height:600px;
  background-image: url(/assets/lyricspic.jpg);}
</style>